
# ============================
# dataset configuration
# ============================
dataset:
  data_dir: "/home/smora"
  train_csv: "kitti_train_separated.csv"
  val_csv: "kitti_val_separated.csv"
  resize_height: 92
  resize_width: 304
  seq_len: 18
  initial_seq: 10
  num_predictions: 8
  num_blocks_per_folder: 2

# ============================
# train configuration
# ============================
training:
  batch_size: 1
  epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.00001
  alpha: 0.9
  beta: 0.8
  ssim_weight: 0.3
  flow_weight: 0.2
  save_checkpoints: true
  checkpoint_dir: runs/alpha_0.9_beta_0.8_epochs_100/checkpoints

# ============================
# Scheduled Sampling
# ============================
scheduled_sampling:
  start: 1.0
  end: 0.2
  decay_rate: 0.99

# ============================
# Paths and results
# ============================
output:
  log_dir: "logs"
  plot_dir: "plots"


# ============================
# Logging 
# ============================
performance_logging:
  enabled: true
  output_file: runs/alpha_0.9_beta_0.8_epochs_100/logs/performance_log.csv
